---
  - name: Create nginx base container
    hosts: localhost
    tasks:
    - name: Pull nginx version 1.15.8 image
      community.docker.docker_container:
        # This removes a deprecation warning
        container_default_behavior: no_defaults
        name: "nginx-base"
        image: "nginx:1.15.8"
        state: started
    - name: Add nginx base container to Ansible hosts
      add_host:
        name: "nginx-base"
        ansible_connection: docker
        ansible_ssh_user: root
  - name: Configure nginx-base for building jcb_demo-nginx image
    hosts: "nginx-base"
    gather_facts: false
    tasks:
      - name: Install python3
        raw: apt update && apt upgrade -y && apt install python3 -y
      - name: Delete nginx.conf
        ansible.builtin.file:
          path: /etc/nginx/nginx.conf
          state: absent
      - name: Copy custom nginx.conf
        ansible.builtin.copy:
          src: ./nginx/nginx.conf
          dest: /etc/nginx/nginx.conf
      - name: Delete default.conf
        ansible.builtin.file:
          path: /etc/nginx/conf.d/default.conf
          state: absent
      - name: Copy custom jcb_demo.conf
        ansible.builtin.copy:
          src: ./nginx/jcb_demo.conf
          dest: /etc/nginx/conf.d/jcb_demo.conf
      - name: Copy static website content
        ansible.builtin.copy:
          src: ./nginx/html
          dest: /usr/share/nginx/
          directory_mode:
        tags:
          - parentdir
      - name: Remove python3 as it's no longer needed
        raw: apt remove python3 -y && apt autoremove -y
  - name: Create jcb_demo-nginx image
    hosts: localhost
    tasks:
      - name: Commit Docker image
        command: docker commit "nginx-base" "jcb_demo-nginx"
  - name: Remove nginx-base as it's no longer needed
    hosts: localhost
    tasks:
      - name: Remove nginx-base container
        community.docker.docker_container:
          # This removes a deprecation warning
          container_default_behavior: no_defaults
          name: nginx-base
          state: absent
          force_kill: yes
