version: '2.0'
services:
  app:
    build: ./app
    ports:
      - 8000:80
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app
    environment:
      - SAMPLE_SIZE=10
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app
